apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: minstrel
build:
  artifacts:
    - image: minstrel
      bazel:
        target: //minstrel:image.tar
        platforms:
          - platform: linux/amd64
            target: //:linux-amd64
          - platform: linux/arm64
            target: //:linux-arm64

  local:
    concurrency: 1
    useBuildkit: true
deploy:
  # kubeContext: byrne
  helm:
    releases:
      - name: minstrel
        namespace: minstrel
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        version: 0.1.0
        setValueTemplates:
          image: "{{.IMAGE_FULLY_QUALIFIED_minstrel}}"
